### ISSUE TITLE
Anler's Architecture sample repo moved

### ISSUE THREAD

**Issue by morhetz** [xgrommx/elm-architecture#1]
It seems that @anler 's repo [moved a month ago](https://github.com/anler/elm-architecture-cover/commit/bd880c445c4ca3b24923830bb42d1fe2fcdc6f50).
`NOTE: Development of this experiment is going on now here: kaleidos/olmo`

**Comment by xgrommx** [comment]
@morhetz Please to provide me PR about this changes.

**Comment by ghost** [comment]
@morhetz Yeap, I moved to another repo, sorry about that, anything you need just tell me :)

**Comment by morhetz** [comment]
@xgrommx, @anler: Great, thanks!
